before:
  hooks:
    - go mod download
    - zip -r templates.zip templates
builds:
- env:
    - CGO_ENABLED=0
  goos:
    - linux
    - darwin
    - windows
  goarch:
    - amd64
archives:
  - name_template: '{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}'
    format: zip
    files:
      - templates.zip
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
release:
  github:
    owner: sivaprasadreddy
    name: spring-boot-cli
  name_template: "{{.Tag}}"
brews:
  -
    tap:
      owner: sivaprasadreddy
      name: homebrew-spring-boot-cli
    homepage: "https://github.com/sivaprasadreddy/spring-boot-cli"
    description: "A CLI utility to generate SpringBoot application"
    test: |
      system "#{bin}/spring-boot-cli --version"
    install: |
      bin.install "spring-boot-cli"