FROM openjdk:11-jdk-slim
VOLUME /tmp{{ "\n" }}
{{- if eq .Metadata.BuildTool "gradle" }}ADD build/libs/{{ .Metadata.ArtifactID }}-{{ .Metadata.ApplicationVersion }}.jar app.jar{{ end -}}
{{- if eq .Metadata.BuildTool "maven" }}ADD target/{{ .Metadata.ArtifactID }}-{{ .Metadata.ApplicationVersion }}.jar app.jar{{ end -}}
{{ "\n" }}RUN sh -c 'touch /app.jar'
ENV JAVA_OPTS="-Xdebug -Xrunjdwp:server=y,transport=dt_socket,address=8787,suspend=n"
ENV SPRING_PROFILES_ACTIVE "default"
EXPOSE 8080 8787
ENTRYPOINT [ "sh", "-c", "java $JAVA_OPTS -Djava.security.egd=file:/dev/./urandom -Dspring.profiles.active=$SPRING_PROFILES_ACTIVE -jar /app.jar" ]
